name: tesla-analysis-f
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Development tools
  - jupyterlab>=4.0.4
  - ipykernel>=6.23.3
  - black>=23.7.0
  - flake8>=6.1.0
  - pytest>=7.3.1
  - isort>=5.12.0
  - mypy>=1.5.1
  # Documentation
  - pip:
      - sphinx>=6.0,<8.2
      - sphinx-rtd-theme>=2.0,<3.0
      - nbsphinx>=0.9,<0.10
      - sphinx-autodoc-typehints>=1.24,<3.0
      - sphinxcontrib-jquery>=4.1
      - -r requirements-dev.txt
