name: tesla-analysis
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # Python and core scientific packages
  - python=3.11
  - numpy=1.24.3
  - pandas=2.0.1
  - scipy=1.10.1
  - matplotlib=3.7.1
  - numba=0.57.0
  
  # Machine learning
  - scikit-learn=1.2.2
  - pytorch=2.0.1
  - cudatoolkit=11.8
  - torchvision=0.15.2
  
  # Statistics and financial tools
  - statsmodels=0.14.0
  - pandas-datareader=0.10.0
  
  # Development tools
  - jupyterlab=4.0.4
  - ipykernel=6.23.3
  - black=23.7.0
  - isort=5.12.0
  - flake8=6.1.0
  - mypy=1.5.1
  - pytest=7.3.1
  - pytest-cov=4.1.0
  
  # CLI and utilities
  - click=8.1.3
  - tqdm=4.65.0
  - pip=23.2.1
  
  # Additional packages via pip
  - pip:
    # Data fetching
    - yfinance==0.2.18
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - lxml==4.9.3
    
    # Visualization
    - plotly==5.15.0
    - dash==2.10.0
    - dash-bootstrap-components==1.4.1
    
    # Utils
    - python-dotenv==1.0.0
    - tenacity==8.2.2
    - pre-commit==3.3.3
    
    # Advanced ML
    - tensorflow==2.13.0
    - transformers==4.30.2
    - pytorch-forecasting==1.0.0
    
    # Web server
    - gunicorn==20.1.0
    - uvicorn==0.22.0