apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesla-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tesla
  template:
    metadata:
      labels:
        app: tesla
    spec:
      containers:
        - name: tesla-container
          image: registry.example.com/tesla-stock-analysis:latest
          ports:
            - containerPort: 8050
          resources:
            limits:
              nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: tesla-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8050
  selector:
    app: tesla
