replicaCount: 1

image:
  repository: ghcr.io/<your-org>/tesla
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8050

resources:
  limits:
    nvidia.com/gpu: 1
