name: Helm Auto-Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          helm package k8s/helm --version $VERSION --app-version $VERSION \
            --destination k8s/helm/packages

      - name: Push Helm Chart to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: k8s/helm/packages/*.tgz
